# Generated by Django 5.2.5 on 2025-10-22 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status', 'due_date'], name='tasks_task_user_id_218dad_idx'),
        ),
    ]
